name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: "ubuntu-18.04"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
        
      - name: Set up Platformio
        run:
            pip install -U platformio
            platformio update

      - name: Build firmware
        run:
            platformio run

      - name: A ver donde corno estamos
        run: 
          sudo apt update
          sudo apt install find
          echo $PWD
          find . -type f -name "*.bin"
          find . -type f -name "*.elf"

      - uses: actions/upload-artifact@v2
        name: Upload firmware files
        with:
          name: firmware 
          path: .pio/build/**/*.bin , .pio/**/**.elf