name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Set up Platformio
        run: pip install -U platformio
          platformio update

      - name: Pull build deps
        run: git submodule update --init --recursive

      - name: Build firmware
        run: platformio run

      - name: Check if firmware files exits
        run: |
          echo "BINARY=$(find . -type f -name "*.bin")" >> $GITHUB_ENV
          echo "ELF=$(find . -type f -name "*.elf")" >> $GITHUB_ENV

      - name: create build tag (1/2)
        run: echo "TEMP_TAG=${BINARY##*/}" >> $GITHUB_ENV
      - name: create build tag (2/2)
        run: echo "BUILD_TAG=$(echo ${TEMP_TAG%.*})" >> $GITHUB_ENV

      - uses: actions/upload-artifact@v2
        name: Upload firmware files
        with:
          name: ${{ env.BUILD_TAG }}
          path: |
            ${{ env.BINARY }}
            ${{ env.ELF }}

  test_firmware:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install deps (testing)
        run: |
          sudo apt update
          sudo apt install -y nodejs npm wget python3 libx11-6 zsh
          sudo npm i -g junit-viewer
          wget https://github.com/xpack-dev-tools/qemu-arm-xpack/releases/download/v2.8.0-11/xpack-qemu-arm-2.8.0-11-linux-x64.tar.gz
          tar xvf ./xpack-qemu-arm-2.8.0-11-linux-x64.tar.gz
          chmod +x ./xpack-qemu-arm-2.8.0-11/bin/qemu-system-gnuarmeclipse
          ./xpack-qemu-arm-2.8.0-11/bin/qemu-system-gnuarmeclipse --version
          echo "TESTING_CI" >> TESTING_CI

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install deps (building)
        run: |
          pip install -U platformio
          platformio update

      - name: Pull build deps
        run: git submodule update --init --recursive

      - name: Build firmware
        run: platformio run

      - name: Run Tests
        run: |
          ./launch_qemu.sh .pio/build/black_f407vg/firmware.bin || true
          python3 generate_report.py

      - name: Generate Report (HTML)
        run: |
          junit-viewer --results=./qemu_report.xml >> openefi_report.html

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        with:
          report_paths: "qemu_report.xml"
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v2
        name: Upload firmware files
        if: always()
        with:
          name: test reports
          path: |
            .pio/build/black_f407vg/firmware.bin
            openefi_report.html
            qemu_report.xml
