name: DOCS

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: "ubuntu-18.04"

    steps:
      - uses: actions/checkout@v3

      - name: install Doxygen && deps
        shell: bash
        run: |
          sudo apt update
          sudo apt install -y wget libncurses-dev doxygen doxygen-doc doxygen-latex doxygen-gui graphviz tree git
        
      - name: Build docs
        env:
          GH_REPO_TOKEN: ${{ secrets.GH_REPO_TOKEN }}
        shell: bash
        run: |
          cd "$GITHUB_WORKSPACE"
          chmod +x ./gen_doc.sh
          ./gen_doc.sh "$GH_REPO_TOKEN"

      - uses: actions/upload-artifact@v3
        name: Upload docs to artifacts
        with:
          name: artifacts
          path: ./